### ISSUE TITLE
Incorporate round trip tests for all inbuilt property types

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#169]
We need a proof that we are writing what we read. The foundation of all `writes` in zio-config is PropertyType. Hence we need tests for all the types that we define within property type.

```scala
val variable = "1000"
LongPropertyType.write(LongPropertyType.read(variable)) ==  variable
```

Examples for which the types can go wrong is "duration"
```scala
DurationProperty.write(DurationPropertyType.read("3 day")) is "3 days"
```
I will consider this issue as one of the higher priority one, and is a very good first issue.

**Comment by zach-albia** [comment]
Working on it.

**Comment by zach-albia** [comment]
@afsalthaj what behavior are we expecting `PropertyType`s to have? For instance, should a roundtrip of `"3 day"` yield `"3 day"` instead of `"3 days"`? Is `"3 days"` really wrong? I've also discovered similar cases where a `BigInt` string like `"005"` would roundtrip into `"5"`. There's also the issue of the lack of precision when doing roundtrips on floating point values, though, I guess clients of `PropertyType` instances should know which instance would be best for some use case.

If we really want to preserve the original, wouldn't we have to store the original in some data type?

Personally, I think the current behavior is fine but I want to know your input on this.

**Comment by afsalthaj** [comment]
Probably, in these scenarios, (where a difference is actually ok), we
should read the written value again to see if there is any difference from
the initially read value.

For certain types, even this property won’t be a success, and in such
situations, the only option is to skip those types.

**Comment by zach-albia** [comment]
> Probably, in these scenarios, (where a difference is actually ok), we
should read the written value again to see if there is any difference from
the initially read value.

Here's the generic assertion I wrote to this effect:

`assert(roundTrip(propType, s).map(parse), isRight(equalTo(parse(s))))`, where `s: String` and `parse: String => A`.

> For certain types, even this property won’t be a success, and in such
situations, the only option is to skip those types.

Understood, I'll see how far it goes.

**Comment by afsalthaj** [comment]
@zach-albia Nice one
