### ISSUE TITLE
Support of Map[String, V]

### ISSUE THREAD

**Issue by pme123** [zio/zio-config#186]
I am working with _PureConfig_.They have great support for a lot of Types:

See https://pureconfig.github.io/docs/built-in-supported-types.html

I couldn't migrate to _zio-config_ because `Map[String, String]` was missing.

Is it possible to support `Map[String, V]` like in _PureConfig_:

> - Maps from String keys to any value type that is on this list;
> - Maps from types convertible to String to any value type that is on this list (must be configured first - see Configurable Converters);

**Comment by afsalthaj** [comment]
This is possible, as zio-config is designed in a way considering all these cases from ground up. I will take this up. Thanks @pme123 for reporting this one.

**Comment by fsvehla** [comment]
@afsalthaj Are you working on this? If not I’d like to take it

**Comment by afsalthaj** [comment]
@fsvehla sorry for late response as I was on my holidays. I am not currently working on it however the current PR which I have raised (it’s in ugly state now) kind of opens the door to support for map. Would you mind giving me some more time before I confirm that you could start working on it?

**Comment by fsvehla** [comment]
Sure

**Comment by afsalthaj** [comment]
When implementing this functionality, I am proposing the following idea.

The idea is to make `map` know the type of `value`. This will behave consistently to `List`

Meaning, the following:
  
  Say, we have a description that says 

```scala

map(list(string("zones")))

```

Let's peal off the above description and try and understand
 1.  `string("zones")` implies `zones` is the key and the value is of type `string`
 2. `list(string(zones))` implies `zones` is the key and the value is of the type `List[String]`
 3. `map(list(string(zones)))` implies `zones` is the key and the value is  of the type  `Map[String, List[String]]`
4. And in fact we can push this idea further forward and make the `key` type parameterised as well. This implies, we should have `Map[K, V]` as the return type  as well, although this can be relatively mind-bending logic because we have only 3 types in `ConfigDescriptor[K, V, A]` of which two of `K` and `V` are already `Strings` in the final implementation layer.

This implies our source of `map(list(string("zones")))`is:
```scala

  zones: {
    syd   : [zone1, zone2]
    melb : [zone1]
    adl    : [zone1]
  }  
```

Starting point to implementing map could be as follows:

```
final case class Map(config: ConfigDescriptor[K, V, A]) extends ConfigDescriptor[K, V, Map[K, V]]
```

```scala
  def map(config: ConfigDescriptor[K, V, A]) =  
     Map(config)
```

In ReadFunctions, make sure the `Sequence` node isn't discarding `Keys` of `Records` while it performs the `reduceInner` logic. 

This will ensure that if the next node in the tree is `Map`, it can form it correctly resulting in solving the above example mentioned, for instance.

We should try to achieve this functionality rather than supporting a  simple primitive of `Map[String, String]`, that makes the library stand out in many ways!

**Comment by afsalthaj** [comment]
@fsvehla 
First of all, Sorry for the delay in responding to you with a yes or no in map.

As part of 1.0 release, zio-config went through quite a bit of changes, and we deprioritised Map in between and focussed on overall design.

While there were  lot of code changes in between, the major design change happened probably last month by introducing `PropertyTree` as the source of truth for all functionalities in zio-config.
During this journey we had to introduce map as well.

Thanks for showing the initiative of contributing to zio-config.

The library is aiming to be one-stop-shop for config management in Scala language, and for the same reason, there are so many issues. We are really looking forward for your support going forward, and in need of more contributors.
