### ISSUE TITLE
Use resource file in SimpleExampleMain

### ISSUE THREAD

**Issue by senia-psm** [zio/zio-config#260]
Currently `SimpleExampleMain` is the only example file that is fails without additional environment configuration.

**Comment by senia-psm** [comment]
@afsalthaj this one still fails locally. It breaks `runAllExamples` in local checks.

**Comment by afsalthaj** [comment]
The reason for closing this issue is
1. Not a burning issue until `runAllExamples` become part of the CI.
2. Let's change the source to something that doesn't require an IO.
3. Adding a resource file and making this example can be a bit too much as an example. 
4. If there are other simple examples already existing, probably I am happy to remove this one as well
