### ISSUE TITLE
Should separate file read and properties handle

### ISSUE THREAD

**Issue by zhiwilliam** [zio/zio-config#430]
Today is my first time try to use this library and it gives me a immediately fail. I tried to load a properties file from my class path (resources root) but I couldn't. The only method I can use is fromPropertiesFile and when I dig into, I found it hard coded FileStreamInput with File. I think it better allow user to specify StreamInput or provide a function to load application.conf etc. That is so popular configure file and I don't know why I cannot find any example on it. It should be in your first website page.

**Comment by zhiwilliam** [comment]
first complain.

**Comment by afsalthaj** [comment]
If there is an example out of 100s of them is missing, feel free to raise a request asking for an example, and I will be more than happy to have that one merged ASAP.

Otherwise, you can directly raise a PR giving an example if you found a working version. If neither of them is possible, and is wording it as a command, I have to close this PR.


Here is the solution. 

```scala

import zio.config._
import magnolia.DeriveConfigDescriptor.descriptor
import typesafe._

  final case class Config(x: String, z: String)

   val result: Either[ReadError[String], Config]  = 
      TypesafeConfigSource.fromDefaultLoader.flatMap(read(descriptor[Config] from _))
  )

```

If you don't want manual configuration

```scala


```

**Comment by afsalthaj** [comment]
You can also retrieve a ZLayer using

```scala

  val config2: Layer[ReadError[String], ZConfig[Config]] = TypesafeConfig.fromDefaultLoader(descriptor[Config])

```

**Comment by afsalthaj** [comment]
Hence closing this issue.
